In [1]:
options(jupyter.rich_display = FALSE)

# Assignment 4: Fundamentals of R Programming

## POP77001 Computer Programming for Social Scientists

## Before submission

- Make sure that you can run all cells without errors
- You can do it by clicking `Kernel`, `Restart & Run All` in the menu above
- Make sure that you save the output by pressing Command+S / CTRL+S
- Rename the file from `04_assignment.ipynb` to `04_assignment_studentnumber_firstname_lastname.ipynb`
- Use Firefox browser for submitting your Jupyter notebook on Blackboard

## Exercise 1: Subsetting (20 points)

Write 3 separate subsetting operations to extract the following elements from the list below:
- All consonants from the first character vector
- Second columns in all dimensions from the array A
- Odd rows from the matrix M

In [2]:
l <- list(
    mapply(assign, letters, 1:26),
    A = array(1:60, c(5,2,3)),
    M = matrix(1:50, c(10,5))
)

In [3]:
l

[[1]]
 a  b  c  d  e  f  g  h  i  j  k  l  m  n  o  p  q  r  s  t  u  v  w  x  y  z 
 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

$A
, , 1

     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10

, , 2

     [,1] [,2]
[1,]   11   16
[2,]   12   17
[3,]   13   18
[4,]   14   19
[5,]   15   20

, , 3

     [,1] [,2]
[1,]   21   26
[2,]   22   27
[3,]   23   28
[4,]   24   29
[5,]   25   30


$M
      [,1] [,2] [,3] [,4] [,5]
 [1,]    1   11   21   31   41
 [2,]    2   12   22   32   42
 [3,]    3   13   23   33   43
 [4,]    4   14   24   34   44
 [5,]    5   15   25   35   45
 [6,]    6   16   26   36   46
 [7,]    7   17   27   37   47
 [8,]    8   18   28   38   48
 [9,]    9   19   29   39   49
[10,]   10   20   30   40   50


In [4]:
# Exercise 1:

# Your code goes here

## Exercise 2: Vectorized operations  (20 points)

Using function `mean()` calculate the proportion of book titles in the vector below that have more than 10 characters in them (including whitespaces).

Tip: You can use `nchar()` function to calculate the number of characters in a vector

In [5]:
books <- c(
  "Dubliners",
  "Ulysses",
  "War and Peace",
  "Normal People",
  "Crime and Punishment",
  "The Picture of Dorian Gray"
)

In [6]:
# Exercise 2:

# Your code goes here

## Exercise 3: Conditional statements and loops  (20 points)

[Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) is a string distance metric that measures how many transformations (insertion, deletion, substitution) are required to convert one string into another. For example, consider words 'cat' and 'can'. Letter 't' in the first word can be substituted with a character 'n' in order for the two words to become identical.

For classical Levenshtein distance each of the transformations has the same cost of 1. In other words, the distance (of 1) is the same between the word pairs 'cat' - 'can' and 'cat' - 'cats'.

Below you can see two character vectors that were transformed to have a single letter as an individual element. Write a loop to compare each of the elements from one string to each of the elements from another string while keeping track of the number of transformations. Print out the result of the transformations count.

In [7]:
char_1 <- unlist(strsplit("kitten", split = ""))
char_2 <- unlist(strsplit("sitting", split = ""))

In [8]:
char_1

[1] "k" "i" "t" "t" "e" "n"

In [9]:
char_2

[1] "s" "i" "t" "t" "i" "n" "g"

In [10]:
# Exercise 3:

# Your code goes here

## Exercise 4: Defining and calling functions (20 points)

Let's revisit [Euclidean distance](https://en.wikipedia.org/wiki/Euclidean_distance) from the previous assignment. As you remember Euclidean distance between two points gives the length of a line segment between them (as the crow flies distance).

Write a function that takes two vectors of arbitrary lengths as coordinates and calculates Euclidean distance between them. Do not use built-in `dist()` function.

Test the implemented function on the following inputs:
- `c(3, 1, 5, 7, 1)` and `c(4, 5, 2, 7, 1)`
- `c(12, 0, 15, 1, 2)` and `c(0, 10, 1, 9, 6)`

Tip: You can revisit the Python solution and re-implement it in R

In [11]:
# Exercise 4:

# Your code goes here

## Exercise 5: Fibonacci sequence (20 points)

We already encountered [Fibonacci sequence](https://en.wikipedia.org/wiki/Fibonacci_number) in this module before. Recall that:
- Fibonacci sequence starts with the first element equal to 0 and the second element equal to 1
- All subsequent elements are the sums of the preceeding two elements
- The beginning of the sequence then looks like this: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, ...]

Implement a function that takes a vector of integers as an input and returns a vector of numbers from Fibonacci sequence, whose indices correspond to the integers from the input vector.

Test the implemented function on the following inputs:
- `10`
- `c(1, 2, 3, 4, 5)`
- `c(3, 9, 12)`

Tip: You may choose to solve a problem with recursion, however, this is not necessary.

In [12]:
# Exercise 5:

# Your code goes here